### ISSUE TITLE
您好，想寻求CCKS电子病历数据集，非常着急，您如果看到，希望可以尽快联系我邮箱：1250484643@qq.com，十分感谢

### ISSUE THREAD

**Issue by 123-HA** [lingluodlut/Chinese-BioNLP#1]
您好，想寻求CCKS电子病历数据集，非常着急，您如果看到，希望可以尽快联系我邮箱：1250484643@qq.com，十分感谢

**Comment by lingluodlut** [comment]
你好。一般CCKS电子病历数据集不是公开发布的，你可以试着联系一下主办方。此外，由中国中文信息学会医疗健康与生物信息处理专业委员会在公开了中文医疗信息处理挑战榜CBLUE(Chinese Biomedical Language Understanding Evaluation)，里面有相关任务的数据可以下载。

**Comment by 123-HA** [comment]
好的，谢谢😊



---原始邮件---
发件人: "ling ***@***.***&gt;
发送时间: 2022年3月30日(周三) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lingluodlut/Chinese-BioNLP] ***@***.***，十分感谢 (Issue #1)




 
你好。一般CCKS电子病历数据集不是公开发布的，你可以试着联系一下主办方。此外，由中国中文信息学会医疗健康与生物信息处理专业委员会在公开了中文医疗信息处理挑战榜CBLUE(Chinese Biomedical Language Understanding Evaluation)，里面有相关任务的数据可以下载。
