### ISSUE TITLE
关于 CCKS 2017 task2 数据集的疑问

### ISSUE THREAD

**Issue by OStars** [lingluodlut/Chinese-BioNLP#2]
您好，很感谢您对 ccks 系列数据集做的整理。我在使用 ccks 2017 task2 数据集的过程中发现，我阅读过的论文中的统计结果都与您记录的一致 (如下表)，对于数据集的描述也大多为 “其中训练集包括300个医疗记录，测试集包含100个医疗记录”。

|  | 症状体征|检查检验|疾病诊断|治疗|身体部位|总数| 
| :----: | :----: | :----: | :----: | :----: | :----: | :----: |
| 训练集 | 7,831	| 9,546	| 722 | 1,048 | 10,719 | 29,866 |
| 测试集 | 2,311	| 3,143 | 553 | 465 | 3,021 | 9,493 |

我对此有三个疑问：
1. 我在[竞赛平台](https://www.biendata.xyz/competition/CCKS2017_2/data/)上下载的测试集是不带标签的，测试集的评测需要上传到[竞赛平台](https://www.biendata.xyz/competition/CCKS2017_2/make-submission/)上评测(现已关闭)，如何能统计测试集的实体信息？
2. 我在[ccks 官网](https://www.sigkg.cn/ccks2017/?page_id=51)上下载的[任务描述文件](http://cips-upload.bj.bcebos.com/ccks2017/CCKS2017%20CNER%20Task%20Definition.docx)中指出 “本任务采用的数据集由北京极目云健康科技有限公司提供，数据来源于其云医院平台的真实电子病历数据，共计800条（单个病人单次就诊记录），经脱敏处理，仅限CCKS 2017 竞赛评测用。”，与 “其中训练集包括300个医疗记录，测试集包含100个医疗记录” 有所出入
3. 我统计的训练集实体信息和上表出入较大 ([训练集](http://cips-upload.bj.bcebos.com/ccks2017/training%20dataset%201-200.zip)我是从[ccks 官网](https://www.sigkg.cn/ccks2017/?page_id=51)下载的))

|  | 症状体征|检查检验|疾病诊断|治疗|身体部位|总数| 
| :----: | :----: | :----: | :----: | :----: | :----: | :----: |
| 训练集 | 6187	| 5785	| 604 | 712 | 8310 | 21598|
| 测试集 | -	| - | - | - | - | - |

因为 ccks 2017 确实已经过去很久了，所以不清楚这几年中是否发生了变化，如果您有和您记录的信息一致的数据集，是否可以共享给我，或者是否可以给我提供正确的获取途径，多有打扰，希望您能回复。

**Comment by lingluodlut** [comment]
你好，我印象中CCKS2017当时评测的时候训练数据更新过几版，官网提供的可能是最初的版本。因为我们当时是参赛队伍，当时签署了数据协议能够使用最终版本的数据，包括带标准答案的测试集。当时数据协议中，我们不允许分享数据，只能通过联系主办方签署数据协议后要数据。好像现在电子病历NLP大多会使用cblue数据集，https://tianchi.aliyun.com/cblue，你可以参考。

**Comment by OStars** [comment]
> 你好，我印象中CCKS2017当时评测的时候训练数据更新过几版，官网提供的可能是最初的版本。因为我们当时是参赛队伍，当时签署了数据协议能够使用最终版本的数据，包括带标准答案的测试集。当时数据协议中，我们不允许分享数据，只能通过联系主办方签署数据协议后要数据。好像现在电子病历NLP大多会使用cblue数据集，[https://tianchi.aliyun.com/cblue，你可以参考。](https://tianchi.aliyun.com/cblue%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E3%80%82)

好的谢谢！
